canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Raphael Thomas"
title               = "Raphael Thomas"
pluralizelisttitles = false

[permalinks]
blog  = "blog/:slug/"

# [[menu.main]]
# name                   = "Blog"
# weight                 = -120
# identifier             = "blog"
# url                    = "/blog/"

# [[menu.main]]
# name                   = "About"
# weight                 = -100
# identifier             = "about"
# url                    = "/about/"

[params]
include_rss            = true
latestpostscount       = 5
i18n_flags             = false
author                 = "Raphael Thomas"
dateform               = "2006-01-02"
dateformfull           = "2006-01-02 15:04:05 MST"
# description            = ""
extracssfiles          = [ "/css/overrides.css", "/css/map.css" ]
lang                   = "en"
# faviconfile            = "img/leaf.ico"
github                 = "https://github.com/raphaelthomas"
instagram              = "https://www.instagram.com/raphael_thomas/"
linkedin               = "https://www.linkedin.com/in/raphael-seebacher/"
noshowreadtime         = false
selfintro              = "engineer · officer · bookworm · crossfitter · radio man · photography explorer"
highlightjs            = true
# highlightjslanguages = ["go"]
# highlightjsStyle     = "darcula"
piwik                  = false
gitalk                 = false
gravatar               = "cb979cc3781fd53475adc366bcc57731"
